#+TITLE: 🌍 of 🦢 🦢 🦢
#+options: f:t

**** I'm [[https://t.me/taoscienceskyrocket][Tao]], your friendly Kubernetes, Dev[Sec]Ops Architect 👷

I believe in dogfooding your own code and selfhost everything I can get away with, from Kubernetes clusters to Docker Swarms. In my spare time I hack on my homeserver [[https://traefik.hansen.agency][mother]] and direct little [[https://tube.hansen.agency][films]] of joy.

I :heart: declarative, immutable infrastructure: ensuring predictable state and writing inheritable manifests makes teams go faster with fewer mistakes.

I've been in crypto since 2016 and spent all of 2019 daytrading while earning my PADI Divemaster certification and researching Islam for an unreleased short film in Dahab, Egypt. My portfolio today is a mix of safe, risky and long bets: from elastic supply Bitcoins, reflect tokens on the Binance Smart Chain, to Cardano and Polkadot.

Emacs is my lifeblood. 

*** Experience
- 2017-07 - 2019-09 - Standard Library - Los Angeles, California
  + *DevOps Engineer*

    Designed and deployed infrastructure powered by Nix and NixOps for Ace Hotel's Sister City robo-hotel in NYC.
    
- 2019-10 - Present - Molecular Quantum Solutions - Copenhagen, Denmark
  + *Lead DevOps Engineer*

    Kubernetes and CI/CD architect of 3 clusters running on AWS EKS, baremetal and Contabo.

    Built secrets pipelines with Vault and SOPS; CI/CD with GitHub Actions, Flux v2, and containers powered by Nix.

    High availability databases powered by Zalando's PostgreSQL Operator.
*** Education
- *Master of Fine Arts* - Funen Art Academy - 2020
- Divemaster - Seven Heaven Divers - 2019
 
*** Skills
- Orchestration
  + Kubernetes
    - OpenShift, MicroK8s, Charmed Kubernetes, RKE, Typhoon
- Big Cloud
  + AWS
  + OCI
  + Hetzner
- Web and Backend
  + Traefik
  + Nginx
  + PostgreSQL
- Languages
  + Bash, fish
  + Nix
  + Terraform HCL
- Tools
  + Terraform
  + Ansible
