#+TITLE: A World of 🦢 🦢 🦢
#+options: f:t

I'm [[https://t.me/taoscienceskyrocket][Tao]] [fn:1], your friendly Kubernetes, Dev[Sec]Ops Architect 👷

I have a deep passion for open source software. When not tending to the machine spirits of a server cluster somewhere, I hack on [[https://traefik.hansen.agency][mother]] and direct little [[https://tube.hansen.agency][films]] of joy.

#+HTML: <script async src="https://telegram.org/js/telegram-widget.js?11" data-telegram-post="netmother/2" data-width="100%"></script>

*** Experience
- 2017-07 - 2019-09 - Standard Library - Los Angeles, California
  + DevOps Engineer

    Designed and deployed server infrastructure for Ace Hotel's Sister City robo-hotel using AWS and Nix resources.
- 2019-10 - Present - Molecular Quantum Solutions - Copenhagen, Denmark
  + Chief Operations Architect

    Built Kubernetes stack from the ground up: secrets management, docker container auto-build pipeline, and documentation for cloud-agnostic deployment on AWS, IBM Cloud, Google Cloud, and Azure.
*** Education
- Master of Fine Arts - Funen Art Academy - 2020
 
*** Skills
- Orchestration
  + Docker Swarm :whale:
  + Kubernetes
    - OpenShift, K3s, and Vanilla :icecream:
- Web and Backend
  + Traefik
  + Nginx
  + PostgreSQL
- Languages
  + Bash
  + Racket
  + Go
  + Python
  + Nix

[fn:1] worldofgeese@humblemail.com
